---
- name: Check for /etc/rhosp-release
  stat:
      path: "/etc/rhosp-release"
  register: rhosp_release_file

- name: Get /etc/rhosp-release content
  command: cat /etc/rhosp-release
  register: rhosp_release_content
  when: rhosp_release_file.stat.exists

- name: Set overcloud_version from /etc/rhosp-release output
  set_fact:
      overcloud_version: "{{ rhosp_release_content.stdout | regex_replace('^Red Hat OpenStack Platform release ([0-9]+)\\.\\d+\\s.*$', '\\1') }}"
  when: rhosp_release_file.stat.exists

- name: Get nova version
  shell: nova-manage --version 2>&1 | awk -F . '{print $1}'
  register: nova_version
  when: not rhosp_release_file.stat.exists

- name: Set overcloud_version from nova-manage output
  vars:
      version_map:
          - nova_version: '15'
            rhos_version: '11'
          - nova_version: '14'
            rhos_version: '10'
          - nova_version: '13'
            rhos_version: '9'
          - nova_version: '12'
            rhos_version: '8'
          - nova_version: '2015'
            rhos_version: '7'
  set_fact:
      overcloud_version: "{{ (version_map|selectattr('nova_version', 'equalto', nova_version.stdout)|first)['rhos_version'] }}"
  when: not rhosp_release_file.stat.exists
